import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Shared/Navbar/Navbar";
import Footer from "./Shared/Footer/Footer";
import ToastProvider from "@/provider/ToastProvider";


import localFont from "next/font/local";

const lato = localFont({
  src: "./fonts/Lato-Regular.ttf",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased `}>
        <div className="w-full md:w-full lg:w-[85%] mx-auto flex flex-col justify-center">
          <ToastProvider />
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
